### ISSUE TITLE
`get_detailed_servers()` "too manu values to unpack (expected 2)

### ISSUE THREAD

**Issue by tarraschk** [Cyberwatch/cyberwatch_api_toolbox#11]
Script :

```
# ping.py
from cbw_api_toolbox.cbw_api import CBWApi

API_KEY = ''
SECRET_KEY = ''
API_URL = ''

CBWApi(API_URL, API_KEY, SECRET_KEY).ping()

servers = CBWApi(API_URL, API_KEY, SECRET_KEY).get_detailed_servers()

category_by_groups = {}

# append each server to a group by category dict
for server in servers:
    if server and server.groups:
        for group in server.groups:
            if group.name not in category_by_groups:
                category_by_groups[group.name] = {}

            concerned_group = category_by_groups[group.name]

            if server.category not in concerned_group:
                concerned_group[server.category] = []

            concerned_group[server.category].append(server)

for group in category_by_groups:
    print("--- GROUP : {0} ---".format(group))

    for category in category_by_groups[group]:
        print("** CATEGORY : {0} **".format(category))

        for computer in category_by_groups[group][category]:
            print("{0} with hostname : {1}".format(category, computer.hostname))
```

Exécution du script :

```
$ python3 ping.py
OK
Traceback (most recent call last):
  File "ping.py", line 10, in <module>
    servers = CBWApi(API_URL, API_KEY, SECRET_KEY).get_detailed_servers()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cbw_api_toolbox/cbw_api.py", line 67, in get_detailed_servers
    return [self.server(server.server_id) for server in self.servers()]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cbw_api_toolbox/cbw_api.py", line 67, in <listcomp>
    return [self.server(server.server_id) for server in self.servers()]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cbw_api_toolbox/cbw_api.py", line 63, in server
    return CBWParser().parse(CBWServer, self._request(ROUTE_SERVERS, "GET", [server_id]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/cbw_api_toolbox/cbw_api.py", line 39, in _request
    verify=self.verify_ssl)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
    self.prepare_body(data, files, json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 507, in prepare_body
    body = self._encode_params(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 97, in _encode_params
    for k, vs in to_key_val_list(data):
ValueError: too many values to unpack (expected 2)
```

=> Le ping fonctionne, mais l'appel à get_detailed_servers() plante avec le message d'erreur indiqué.

Tests faits sur l'environnement de démonstration, avec des machines ayant plusieurs groupes.

**Comment by tarraschk** [comment]
Problème réglé dans mes tests ce soir (j'ai désinstallé la lib, puis réinstallé)
