### ISSUE TITLE
Catch exceptions when the URL is not provided or invalid

### ISSUE THREAD

**Issue by fakenine** [Cyberwatch/cyberwatch_api_toolbox#3]
Currently, when the `API_URL` is not provided or invalid, the following message appears:

```bash
Traceback (most recent call last):
  File "ping.py", line 7, in <module>
    CBWApi(API_URL, API_KEY, SECRET_KEY).ping()
  File "/home/samy/code/cyberwatch_api_toolbox/cbw_api_toolbox/cbw_api.py", line 47, in ping
    result = self._request(ROUTE_GET_PING)
  File "/home/samy/code/cyberwatch_api_toolbox/cbw_api_toolbox/cbw_api.py", line 36, in _request
    verify=self.verify_ssl)
  File "/home/samy/.local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/samy/.local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/samy/.local/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/home/samy/.local/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/samy/.local/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/home/samy/.local/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/api/v2/ping': No schema supplied. Perhaps you meant http:///api/v2/ping?
```

This exception should be catched in order to print a human-readable error message instead, inviting the user to provide a valid URL.

**Comment by fakenine** [comment]
@Herklos Thanks
